"""Pokémon Showdown protocol parser.

This package aggregates raw protocol messages into complete semantic events.

Public entry point: :class:`Parser`.
"""

from showdown_sdk.classes.parser.battle_state_handler import BattleStateHandler
from showdown_sdk.classes.parser.context import (
    EffectHandler,
    EffectParseContext,
    EffectPredicate,
    EffectRule,
    MoveParseState,
    ParsedCondition,
    ProtocolContext,
    TargetModifiers,
)
from showdown_sdk.classes.parser.context_updates import update_protocol_context
from showdown_sdk.classes.parser.events.base import (
    BaseEvent,
    DiscardedEvent,
    UnhandledEvent,
    unhandled_event,
)
from showdown_sdk.classes.parser.events.battle import (
    AbilityEvent,
    BattleEndEvent,
    BattleEvent,
    BattleStartEvent,
    CantEvent,
    ClearAllBoostsEvent,
    ClearBoostsEvent,
    ClearNegativeBoostsEvent,
    CopyBoostEvent,
    CustomShowdownBattleStateEvent,
    DamageEvent,
    DecisionRequestEvent,
    DesyncEvent,
    DetailsChangeEvent,
    FormeChangeEvent,
    GameGenEvent,
    GameTierEvent,
    GameTypeEvent,
    HealEvent,
    ItemEvent,
    MajorStatusEvent,
    MinorStatusActivationEvent,
    MinorStatusEvent,
    MoveActivationEvent,
    MoveCopiedEvent,
    MoveEvent,
    MovePrepareEvent,
    PartialTrapEvent,
    PerishCountEvent,
    PlayerEvent,
    PokemonSwitchEvent,
    RoomEvent,
    SetHpEvent,
    SideConditionEvent,
    SingleMoveEvent,
    StatChangeEvent,
    StatSetEvent,
    TeamCureEvent,
    TeamPreviewRequestEvent,
    TransformEvent,
    TurnEvent,
    TypeChangeEvent,
    UpkeepEvent,
    WeatherEvent,
)
from showdown_sdk.classes.parser.events.lobby import (
    FormatsEvent,
    LobbyEvent,
    NameTakenEvent,
    PrivateMessageEvent,
    TeamRejectedEvent,
    TeamValidEvent,
    UpdateUserEvent,
    UserNotFoundEvent,
)
from showdown_sdk.classes.parser.exceptions import (
    InvalidActionError,
    ObsoleteRequestIdError,
    ParserException,
    WrongRoomException,
)
from showdown_sdk.classes.parser.fields import (
    is_percentage_hp,
    make_move_source,
    parse_condition,
    parse_effect_source,
    parse_level,
    parse_minor_status,
    parse_move_origin,
    parse_pokemon_details,
    parse_pokemon_ident,
    parse_side_ident,
)
from showdown_sdk.classes.parser.handlers.commands import (
    COMMAND_HANDLERS,
    CommandHandler,
    handle_battle_end,
    handle_cant,
    handle_switch,
    handle_turn,
)
from showdown_sdk.classes.parser.handlers.moves import (
    parse_move_group,
    parse_standalone_effect,
)
from showdown_sdk.classes.parser.handlers.requests import parse_request_event
from showdown_sdk.classes.parser.models import (
    EffectSource,
    PokemonDetails,
    PokemonIdent,
    ProtocolAnnotation,
    ProtocolMessage,
    RequestMove,
    RequestPokemon,
)
from showdown_sdk.classes.parser.parser import Parser
from showdown_sdk.classes.parser.parsers.base import MessageParser
from showdown_sdk.classes.parser.parsers.battle import BattleParser, ParseResult
from showdown_sdk.classes.parser.parsers.lobby import LobbyParser
from showdown_sdk.classes.parser.protocol import (
    annotation_value,
    extract_protocol_line,
    has_annotation,
    is_ignored_message,
    is_move_boundary,
    parse_protocol_message,
    require_arguments,
)
from showdown_sdk.classes.parser.reducers import reduce_battle_state

# ruff: noqa: RUF022
__all__ = [
    # Entry point
    "Parser",
    "ParseResult",
    # Parsers
    "MessageParser",
    "BattleParser",
    "LobbyParser",
    # Lobby events
    "LobbyEvent",
    "UpdateUserEvent",
    "NameTakenEvent",
    "FormatsEvent",
    "PrivateMessageEvent",
    "TeamRejectedEvent",
    "TeamValidEvent",
    "UserNotFoundEvent",
    # Exceptions
    "ParserException",
    "WrongRoomException",
    "InvalidActionError",
    "ObsoleteRequestIdError",
    # Meta models
    "ProtocolAnnotation",
    "ProtocolMessage",
    "PokemonIdent",
    "PokemonDetails",
    "RequestMove",
    "RequestPokemon",
    "EffectSource",
    # Events
    "BaseEvent",
    "BattleEvent",
    "MoveEvent",
    "DamageEvent",
    "HealEvent",
    "MinorStatusEvent",
    "MajorStatusEvent",
    "MoveCopiedEvent",
    "MinorStatusActivationEvent",
    "StatChangeEvent",
    "MovePrepareEvent",
    "TeamCureEvent",
    "ClearAllBoostsEvent",
    "ClearBoostsEvent",
    "CopyBoostEvent",
    "ClearNegativeBoostsEvent",
    "SetHpEvent",
    "SideConditionEvent",
    "PokemonSwitchEvent",
    "TransformEvent",
    "AbilityEvent",
    "StatSetEvent",
    "MoveActivationEvent",
    "ItemEvent",
    "CantEvent",
    "DecisionRequestEvent",
    "PerishCountEvent",
    "TurnEvent",
    "WeatherEvent",
    "BattleEndEvent",
    "BattleStartEvent",
    "PlayerEvent",
    "UnhandledEvent",
    "DiscardedEvent",
    "SingleMoveEvent",
    "TypeChangeEvent",
    "FormeChangeEvent",
    "RoomEvent",
    "UpkeepEvent",
    "DesyncEvent",
    "DetailsChangeEvent",
    "GameGenEvent",
    "GameTierEvent",
    "GameTypeEvent",
    "CustomShowdownBattleStateEvent",
    "PartialTrapEvent",
    "TeamPreviewRequestEvent",
    "unhandled_event",
    # Context
    "ProtocolContext",
    "ParsedCondition",
    "TargetModifiers",
    "EffectParseContext",
    "MoveParseState",
    "EffectHandler",
    "EffectPredicate",
    "EffectRule",
    # Protocol helpers
    "parse_protocol_message",
    "extract_protocol_line",
    "annotation_value",
    "has_annotation",
    "is_ignored_message",
    "is_move_boundary",
    "require_arguments",
    # Field parsers
    "parse_pokemon_ident",
    "parse_pokemon_details",
    "parse_move_origin",
    "parse_condition",
    "parse_level",
    "is_percentage_hp",
    "parse_minor_status",
    "parse_side_ident",
    "parse_effect_source",
    "make_move_source",
    # Command handlers
    "CommandHandler",
    "COMMAND_HANDLERS",
    "handle_switch",
    "handle_turn",
    "handle_cant",
    "handle_battle_end",
    "parse_move_group",
    "parse_standalone_effect",
    "parse_request_event",
    # Protocol context
    "update_protocol_context",
    # Reducers / battle state
    "reduce_battle_state",
    "BattleStateHandler",
]
